# --------------------------------
# name: Snowflake Role Hierarchy
# owner: admin
# description: Define parent-child relationships
# version: 1.0
# --------------------------------

roles:
  SECURITY_ADMIN: [DATA_ADMIN]
  DATA_ADMIN: [DEVELOPER]
  DEVELOPER: [ANALYST]
  ANALYST: []

privileges:
  account:
    CREATE ROLE: [SECURITY_ADMIN]
    CREATE USER: [SECURITY_ADMIN]
    CREATE WAREHOUSE: [SECURITY_ADMIN]
    CREATE DATABASE: [SECURITY_ADMIN]
    MONITOR USAGE : [SECURITY_ADMIN]

  warehouse:
    COMPUTE_WH:
    USAGE: [ANALYST]
    MODIFY: [SECURITY_ADMIN]

  database:
    GOVERNANCE:
      USAGE: [ANALYST]
      MODIFY: [DATA_ADMIN]
      CREATE DATABASE ROLE: [DATA_ADMIN]
      CREATE SCHEMA: [DATA_ADMIN]

  schema:
    AUDIT:
      USAGE: [ANALYST]
      MODIFY: [DATA_ADMIN]
      CREATE TABLE: [DEVELOPER]
      CREATE VIEW: [DEVELOPER]
      CREATE TAG: [SECURITY_ADMIN]
    MONITOR:
      USAGE: [ANALYST]
      MODIFY: [DATA_ADMIN]
      CREATE TABLE: [DEVELOPER]
      CREATE VIEW: [DEVELOPER]
    BRONZE:
      USAGE: [ANALYST]
      MODIFY: [DATA_ADMIN]
      CREATE TABLE: [DEVELOPER]
      CREATE VIEW: [DEVELOPER]
      CREATE TAG: [SECURITY_ADMIN]
