# --------------------------------
# name: Snowflake Role Hierarchy
# description: Define parent-child relationships
# --------------------------------

roles:
  # Tier 1 - granular
  DBR_CREATOR:  [DBR_OPERATOR]
  DBR_OPERATOR: [DBR_VIEWER]
  DBR_VIEWER:   []

privileges:
  database:
    USAGE:                [DBR_VIEWER]
    MONITOR:              [DBR_OPERATOR]
    MODIFY:               [DBR_OPERATOR]
    CREATE DATABASE ROLE: [DBR_CREATOR]
    CREATE SCHEMA:        [DBR_CREATOR]

  schema:
    USAGE:                                     [DBR_VIEWER]
    MONITOR:                                   [DBR_OPERATOR]
    MODIFY:                                    [DBR_OPERATOR]
    CREATE TABLE:                              [DBR_CREATOR]
    CREATE VIEW:                               [DBR_CREATOR]
    CREATE STAGE:                              [DBR_CREATOR]
    CREATE PIPE:                               [DBR_CREATOR]
    CREATE MASKING POLICY:                     [DBR_CREATOR]
    CREATE PASSWORD POLICY:                    [DBR_CREATOR]
    CREATE ROW ACCESS POLICY:                  [DBR_CREATOR]
    CREATE MODEL:                              [DBR_CREATOR]
    CREATE MODEL MONITOR:                      [DBR_CREATOR]
    CREATE SNOWFLAKE.ML.CLASSIFICATION:        [DBR_CREATOR]
    CREATE SNOWFLAKE.ML.FORECAST:              [DBR_CREATOR]
    CREATE SNOWFLAKE.ML.ANOMALY_DETECTION:     [DBR_CREATOR]
    CREATE SNOWFLAKE.ML.DOCUMENT_INTELLIGENCE: [DBR_CREATOR]
    CREATE NOTEBOOK:                           [DBR_CREATOR]
    CREATE PACKAGES POLICY:                    [DBR_CREATOR]
    CREATE TAG:                                [DBR_CREATOR]
