snowflake:
  templates:
    admins: &admins
      roles: [SYSADMIN, ACCOUNTADMIN]

    local_admins: &db_admins
      roles: [DE_ADMIN, DE_ENGINEER]

  resources:
    account_roles:
      DE_ADMIN:
        grant_to:
          <<: *admins
      DE_ENGINEER:
        grant_to:
          roles:
            - DE_ADMIN
      DE_VIEWER:
        grant_to:
          roles:
            - DE_ENGINEER
