# --------------------------------
# name: Snowflake Privileges Mapping
# owner: admin
# description: Privilege to Database Roles Matrix
# version: 1.0
# --------------------------------

database:
  roles: [DBR_ADMIN, DBR_CREATOR, DBR_OPERATOR, DBR_VIEWER]
  privileges:
    USAGE: [DBR_VIEWER]
    MONITOR: [DBR_OPERATOR]
    MODIFY: [DBR_OPERATOR]
    CREATE DATABASE ROLE: [DBR_CREATOR]
    CREATE SCHEMA: [DBR_CREATOR]

schema:
  roles: [DBR_ETL, DBR_SECURITY, DBR_ML]
  privileges:
    USAGE: [DBR_VIEWER]
    MONITOR: [DBR_VIEWER]
    MODIFY: [DBR_OPERATOR]
    CREATE TABLE: [DBR_ETL]
    CREATE VIEW: [DBR_ETL]
    CREATE STAGE: [DBR_ETL]
    CREATE PIPE: [DBR_ETL]
    CREATE MASKING POLICY: [DBR_SECURITY]
    CREATE PASSWORD POLICY: [DBR_SECURITY]
    CREATE ROW ACCESS POLICY: [DBR_SECURITY]
    CREATE MODEL: [DBR_ML]
    CREATE MODEL MONITOR: [DBR_ML]
    CREATE SNOWFLAKE.ML.CLASSIFICATION: [DBR_ML]
    CREATE SNOWFLAKE.ML.FORECAST: [DBR_ML]
    CREATE SNOWFLAKE.ML.ANOMALY_DETECTION: [DBR_ML]
    CREATE SNOWFLAKE.ML.DOCUMENT_INTELLIGENCE: [DBR_ML]
    CREATE NOTEBOOK: [DBR_CREATOR]
    CREATE PACKAGES POLICY: [DBR_SECURITY]
    CREATE TAG: [DBR_SECURITY]
