# --------------------------------
# name: Snowflake Account Roles
# owner: security
# description: Define parent-child relationships and privileges
# version: 1.0
# --------------------------------

roles:
  system_role:
    - name: SYSADMIN
      account:  [TERRAFORM_DEV_ADMIN]
      database: []
  ownership_roles:
    DEV: [TERRAFORM_DEV_ADMIN]
  account:
    # MAIN ROLE
    - name: TERRAFORM_DEV_ADMIN
      account:  [WH_LOADING_DEV_ADMIN, WH_TRANSFORMATION_DEV_ADMIN, WH_ANALYTICS_DEV_ADMIN, 
                AC_GLB_DEV_DATA_ENGINEER, AC_GLB_DEV_BUSINESS_INTELLIGENCE, AC_GLB_DEV_DATA_ARCHITECT]
      database: []

    # WAREHOUSE ROLES - Tier 2
    - name: WH_LOADING_DEV_ADMIN
      account:  [WH_LOADING_DEV_USAGE]
      database: []
    - name: WH_LOADING_DEV_USAGE
      account:  []
      database: []
    - name: WH_TRANSFORMATION_DEV_USAGE
      account:  []
      database: []
    - name: WH_TRANSFORMATION_DEV_ADMIN
      account:  [WH_TRANSFORMATION_DEV_USAGE]
      database: []
    - name: WH_ANALYTICS_DEV_USAGE
      account:  []
      database: []
    - name: WH_ANALYTICS_DEV_ADMIN
      account:  [WH_ANALYTICS_DEV_USAGE]
      database: []

    # DATA_ENGINEER GLOBAL ROLE - Tier 2
    - name: AC_GLB_DEV_DATA_ENGINEER
      account:  [AC_BAR_DEV_DATA_ENGINEER, AC_BMX_DEV_DATA_ENGINEER, AC_BEC_DEV_DATA_ENGINEER, AC_BPE_DEV_DATA_ENGINEER, AC_HTC_DEV_DATA_ENGINEER, AC_BUS_DEV_DATA_ENGINEER]
      database: []

    # BUSINESS_INTELLIGENCE GLOBAL ROLE - Tier 2
    - name: AC_GLB_DEV_BUSINESS_INTELLIGENCE
      account:  [AC_BAR_DEV_BUSINESS_INTELLIGENCE, AC_BMX_DEV_BUSINESS_INTELLIGENCE, AC_BEC_DEV_BUSINESS_INTELLIGENCE, AC_BPE_DEV_BUSINESS_INTELLIGENCE, AC_HTC_DEV_BUSINESS_INTELLIGENCE, AC_BUS_DEV_BUSINESS_INTELLIGENCE]
      database: []

    # DATA_ARCHITECT GLOBAL ROLE - Tier 2
    - name: AC_GLB_DEV_DATA_ARCHITECT
      account:  [AC_GLB_DEV_BRONZE_READER, AC_GLB_DEV_SILVER_READER_RV, AC_GLB_DEV_SILVER_READER_BV, AC_GLB_DEV_GOLD_READER]
      database: []

    # DATA_ENGINEER LOCAL ROLES - Tier 3
    - name: AC_BMX_DEV_DATA_ENGINEER
      account:  [BRONZE_GENERAL_BMX_DEV_DEVELOPER, SILVER_GENERAL_BMX_DEV_DEVELOPER_RV, SILVER_GENERAL_BMX_DEV_READER_BV, GOLD_GENERAL_BMX_DEV_READER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BAR_DEV_DATA_ENGINEER
      account:  [BRONZE_GENERAL_BAR_DEV_DEVELOPER, SILVER_GENERAL_BAR_DEV_DEVELOPER_RV, SILVER_GENERAL_BAR_DEV_READER_BV, GOLD_GENERAL_BAR_DEV_READER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BEC_DEV_DATA_ENGINEER
      account:  [BRONZE_GENERAL_BEC_DEV_DEVELOPER, SILVER_GENERAL_BEC_DEV_DEVELOPER_RV, SILVER_GENERAL_BEC_DEV_READER_BV, GOLD_GENERAL_BEC_DEV_READER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BPE_DEV_DATA_ENGINEER
      account:  [BRONZE_GENERAL_BPE_DEV_DEVELOPER, SILVER_GENERAL_BPE_DEV_DEVELOPER_RV, SILVER_GENERAL_BPE_DEV_READER_BV, GOLD_GENERAL_BPE_DEV_READER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_HTC_DEV_DATA_ENGINEER
      account:  [BRONZE_GENERAL_HTC_DEV_DEVELOPER, SILVER_GENERAL_HTC_DEV_DEVELOPER_RV, SILVER_GENERAL_HTC_DEV_READER_BV, GOLD_GENERAL_HTC_DEV_READER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BUS_DEV_DATA_ENGINEER
      account:  [BRONZE_GENERAL_BUS_DEV_DEVELOPER, SILVER_GENERAL_BUS_DEV_DEVELOPER_RV, SILVER_GENERAL_BUS_DEV_READER_BV, GOLD_GENERAL_BUS_DEV_READER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
   
    # BUSINESS_INTELLIGENCE LOCAL ROLES - Tier 3
    - name: AC_BMX_DEV_BUSINESS_INTELLIGENCE
      account:  [BRONZE_GENERAL_BMX_DEV_READER, SILVER_GENERAL_BMX_DEV_READER_RV, SILVER_GENERAL_BMX_DEV_DEVELOPER_BV, GOLD_GENERAL_BMX_DEV_DEVELOPER, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BAR_DEV_BUSINESS_INTELLIGENCE
      account:  [BRONZE_GENERAL_BAR_DEV_READER, SILVER_GENERAL_BAR_DEV_READER_RV, SILVER_GENERAL_BAR_DEV_DEVELOPER_BV, GOLD_GENERAL_BAR_DEV_DEVELOPER, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BEC_DEV_BUSINESS_INTELLIGENCE
      account:  [BRONZE_GENERAL_BEC_DEV_READER, SILVER_GENERAL_BEC_DEV_READER_RV, SILVER_GENERAL_BEC_DEV_DEVELOPER_BV, GOLD_GENERAL_BEC_DEV_DEVELOPER, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BPE_DEV_BUSINESS_INTELLIGENCE
      account:  [BRONZE_GENERAL_BPE_DEV_READER, SILVER_GENERAL_BPE_DEV_READER_RV, SILVER_GENERAL_BPE_DEV_DEVELOPER_BV, GOLD_GENERAL_BPE_DEV_DEVELOPER, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_HTC_DEV_BUSINESS_INTELLIGENCE
      account:  [BRONZE_GENERAL_HTC_DEV_READER, SILVER_GENERAL_HTC_DEV_READER_RV, SILVER_GENERAL_HTC_DEV_DEVELOPER_BV, GOLD_GENERAL_HTC_DEV_DEVELOPER, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BUS_DEV_BUSINESS_INTELLIGENCE
      account:  [BRONZE_GENERAL_BUS_DEV_READER, SILVER_GENERAL_BUS_DEV_READER_RV, SILVER_GENERAL_BUS_DEV_DEVELOPER_BV, GOLD_GENERAL_BUS_DEV_DEVELOPER, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []

    # READER GLOBAL ROLES - Tier 3
    - name: AC_GLB_DEV_BRONZE_READER
      account:  [BRONZE_GENERAL_BAR_DEV_READER, BRONZE_GENERAL_BMX_DEV_READER, BRONZE_GENERAL_BEC_DEV_READER, BRONZE_GENERAL_BPE_DEV_READER, BRONZE_GENERAL_HTC_DEV_READER, BRONZE_GENERAL_BUS_DEV_READER,
                WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_GLB_DEV_SILVER_READER_RV
      account:  [SILVER_GENERAL_BAR_DEV_READER_RV, SILVER_GENERAL_BMX_DEV_READER_RV, SILVER_GENERAL_BEC_DEV_READER_RV, SILVER_GENERAL_BPE_DEV_READER_RV, SILVER_GENERAL_HTC_DEV_READER_RV, SILVER_GENERAL_BUS_DEV_READER_RV,
                WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_GLB_DEV_SILVER_READER_BV
      account:  [SILVER_GENERAL_BAR_DEV_READER_BV, SILVER_GENERAL_BMX_DEV_READER_BV, SILVER_GENERAL_BEC_DEV_READER_BV, SILVER_GENERAL_BPE_DEV_READER_BV, SILVER_GENERAL_HTC_DEV_READER_BV, SILVER_GENERAL_BUS_DEV_READER_BV,
                WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_GLB_DEV_GOLD_READER
      account:  [GOLD_GENERAL_BAR_DEV_READER, GOLD_GENERAL_BMX_DEV_READER, GOLD_GENERAL_BEC_DEV_READER, GOLD_GENERAL_BPE_DEV_READER, GOLD_GENERAL_HTC_DEV_READER, GOLD_GENERAL_BUS_DEV_READER,
                WH_ANALYTICS_DEV_USAGE]
      database: []

    # BRONZE BASE ROLES - Tier 4
    - name: BRONZE_GENERAL_BAR_DEV_DEVELOPER
      account:  []
      database: 
        "01": [SC_BRONZE_AS400_BAR_DB_O, SC_BRONZE_OPE_GLB_DB_O]
    - name: BRONZE_GENERAL_BAR_DEV_READER
      account:  []
      database:
        "01": [SC_BRONZE_AS400_BAR_DB_R, SC_BRONZE_OPE_GLB_DB_R]
    - name: BRONZE_GENERAL_BMX_DEV_DEVELOPER
      account:  []
      database: 
        "01": [SC_BRONZE_E1P_BMX_DB_O, SC_BRONZE_VENDING_BMX_DB_O, SC_BRONZE_OPE_GLB_DB_O]
    - name: BRONZE_GENERAL_BMX_DEV_READER
      account:  []
      database:
        "01": [SC_BRONZE_E1P_BMX_DB_R, SC_BRONZE_VENDING_BMX_DB_R, SC_BRONZE_OPE_GLB_DB_R]
    - name: BRONZE_GENERAL_BEC_DEV_DEVELOPER
      account:  []    
      database: 
        "01": [SC_BRONZE_AS400_BEC_DB_O, SC_BRONZE_OPE_GLB_DB_O]
    - name: BRONZE_GENERAL_BEC_DEV_READER
      account:  []
      database:
        "01": [SC_BRONZE_AS400_BEC_DB_R, SC_BRONZE_OPE_GLB_DB_R]
    - name: BRONZE_GENERAL_BPE_DEV_DEVELOPER
      account:  []    
      database: 
        "01": [SC_BRONZE_AS400_BPE_DB_O, SC_BRONZE_OPE_GLB_DB_O]
    - name: BRONZE_GENERAL_BPE_DEV_READER
      account:  []
      database:
        "01": [SC_BRONZE_AS400_BPE_DB_R, SC_BRONZE_OPE_GLB_DB_R]
    - name: BRONZE_GENERAL_HTC_DEV_DEVELOPER
      account:  []    
      database: 
        "01": [SC_BRONZE_AS400_HTC_DB_O, SC_BRONZE_OPE_GLB_DB_O]
    - name: BRONZE_GENERAL_HTC_DEV_READER
      account:  []
      database:
        "01": [SC_BRONZE_AS400_HTC_DB_R, SC_BRONZE_OPE_GLB_DB_R]
    - name: BRONZE_GENERAL_BUS_DEV_DEVELOPER
      account:  []    
      database: 
        "01": [SC_BRONZE_SNOWF_BUS_DB_O, SC_BRONZE_OPE_GLB_DB_O]
    - name: BRONZE_GENERAL_BUS_DEV_READER
      account:  []
      database:
        "01": [SC_BRONZE_SNOWF_BUS_DB_R, SC_BRONZE_OPE_GLB_DB_R]
    - name: BRONZE_GENERAL_GLB_DEV_DEVELOPER
      account:  []    
      database: 
        "01": [SC_BRONZE_OPE_GLB_DB_O]
    - name: BRONZE_GENERAL_GLB_DEV_READER
      account:  []
      database:
        "01": [SC_BRONZE_OPE_GLB_DB_R]
    
    # SILVER BASE ROLES - Tier 4
    - name: SILVER_GENERAL_BAR_DEV_DEVELOPER_RV
      account:  []    
      database: 
        "01": [SC_SILVER_BAR_RV_DB_O, SC_SILVER_GLB_RV_DB_O]
    - name: SILVER_GENERAL_BAR_DEV_READER_RV
      account:  []
      database:
        "01": [SC_SILVER_BAR_RV_DB_R, SC_SILVER_GLB_RV_DB_R]
    - name: SILVER_GENERAL_BAR_DEV_DEVELOPER_BV
      account:  []    
      database: 
        "01": [SC_SILVER_BAR_BV_DB_O, SC_SILVER_GLB_BV_DB_O]
    - name: SILVER_GENERAL_BAR_DEV_READER_BV
      account:  []
      database:
        "01": [SC_SILVER_BAR_BV_DB_R, SC_SILVER_GLB_BV_DB_R]
    - name: SILVER_GENERAL_BMX_DEV_DEVELOPER_RV
      account:  []    
      database: 
        "01": [SC_SILVER_BMX_RV_DB_O, SC_SILVER_GLB_RV_DB_O]
    - name: SILVER_GENERAL_BMX_DEV_READER_RV
      account:  []
      database:
        "01": [SC_SILVER_BMX_RV_DB_R, SC_SILVER_GLB_RV_DB_R]
    - name: SILVER_GENERAL_BMX_DEV_DEVELOPER_BV
      account:  []    
      database: 
        "01": [SC_SILVER_BMX_BV_DB_O, SC_SILVER_GLB_BV_DB_O]
    - name: SILVER_GENERAL_BMX_DEV_READER_BV
      account:  []
      database:
        "01": [SC_SILVER_BMX_BV_DB_R, SC_SILVER_GLB_BV_DB_R]
    - name: SILVER_GENERAL_BEC_DEV_DEVELOPER_RV
      account:  []    
      database: 
        "01": [SC_SILVER_BEC_RV_DB_O, SC_SILVER_GLB_RV_DB_O]
    - name: SILVER_GENERAL_BEC_DEV_READER_RV
      account:  []
      database:
        "01": [SC_SILVER_BEC_RV_DB_R, SC_SILVER_GLB_RV_DB_R]
    - name: SILVER_GENERAL_BEC_DEV_DEVELOPER_BV
      account:  []    
      database: 
        "01": [SC_SILVER_BEC_BV_DB_O, SC_SILVER_GLB_BV_DB_O]
    - name: SILVER_GENERAL_BEC_DEV_READER_BV
      account:  []
      database:
        "01": [SC_SILVER_BEC_BV_DB_R, SC_SILVER_GLB_BV_DB_R]
    - name: SILVER_GENERAL_BPE_DEV_DEVELOPER_RV
      account:  []    
      database: 
        "01": [SC_SILVER_BPE_RV_DB_O, SC_SILVER_GLB_RV_DB_O]
    - name: SILVER_GENERAL_BPE_DEV_READER_RV
      account:  []
      database:
        "01": [SC_SILVER_BPE_RV_DB_R, SC_SILVER_GLB_RV_DB_R]
    - name: SILVER_GENERAL_BPE_DEV_DEVELOPER_BV
      account:  []    
      database: 
        "01": [SC_SILVER_BPE_BV_DB_O, SC_SILVER_GLB_BV_DB_O]
    - name: SILVER_GENERAL_BPE_DEV_READER_BV
      account:  []
      database:
        "01": [SC_SILVER_BPE_BV_DB_R, SC_SILVER_GLB_BV_DB_R]
    - name: SILVER_GENERAL_HTC_DEV_DEVELOPER_RV
      account:  []    
      database: 
        "01": [SC_SILVER_HTC_RV_DB_O, SC_SILVER_GLB_RV_DB_O]
    - name: SILVER_GENERAL_HTC_DEV_READER_RV
      account:  []
      database:
        "01": [SC_SILVER_HTC_RV_DB_R, SC_SILVER_GLB_RV_DB_R]
    - name: SILVER_GENERAL_HTC_DEV_DEVELOPER_BV
      account:  []    
      database: 
        "01": [SC_SILVER_HTC_BV_DB_O, SC_SILVER_GLB_BV_DB_O]
    - name: SILVER_GENERAL_HTC_DEV_READER_BV
      account:  []
      database:
        "01": [SC_SILVER_HTC_BV_DB_R, SC_SILVER_GLB_BV_DB_R]
    - name: SILVER_GENERAL_BUS_DEV_DEVELOPER_RV
      account:  []    
      database: 
        "01": [SC_SILVER_BUS_RV_DB_O, SC_SILVER_GLB_RV_DB_O]
    - name: SILVER_GENERAL_BUS_DEV_READER_RV
      account:  []
      database:
        "01": [SC_SILVER_BUS_RV_DB_R, SC_SILVER_GLB_RV_DB_R]
    - name: SILVER_GENERAL_BUS_DEV_DEVELOPER_BV
      account:  []    
      database: 
        "01": [SC_SILVER_BUS_BV_DB_O, SC_SILVER_GLB_BV_DB_O]
    - name: SILVER_GENERAL_BUS_DEV_READER_BV
      account:  []
      database:
        "01": [SC_SILVER_BUS_BV_DB_R, SC_SILVER_GLB_BV_DB_R]
    - name: SILVER_GENERAL_GLB_DEV_DEVELOPER_RV
      account:  []    
      database: 
        "01": [SC_SILVER_GLB_RV_DB_O]
    - name: SILVER_GENERAL_GLB_DEV_READER_RV
      account:  []
      database:
        "01": [SC_SILVER_GLB_RV_DB_R]
    - name: SILVER_GENERAL_GLB_DEV_DEVELOPER_BV
      account:  []    
      database: 
        "01": [SC_SILVER_GLB_BV_DB_O]
    - name: SILVER_GENERAL_GLB_DEV_READER_BV
      account:  []
      database:
        "01": [SC_SILVER_GLB_BV_DB_R]

    # GOLD BASE ROLES - Tier 4
    - name: GOLD_GENERAL_BAR_DEV_DEVELOPER
      account:  []    
      database: 
        "01": [SC_GOLD_BAR_DB_O, SC_GOLD_GLB_DB_O]
    - name: GOLD_GENERAL_BAR_DEV_READER
      account:  []
      database:
        "01": [SC_GOLD_BAR_DB_R, SC_GOLD_GLB_DB_R]
    - name: GOLD_GENERAL_BMX_DEV_DEVELOPER
      account:  []    
      database: 
        "01": [SC_GOLD_BMX_DB_O, SC_GOLD_GLB_DB_O]
    - name: GOLD_GENERAL_BMX_DEV_READER
      account:  []
      database:
        "01": [SC_GOLD_BMX_DB_R, SC_GOLD_GLB_DB_R]
    - name: GOLD_GENERAL_BEC_DEV_DEVELOPER
      account:  []    
      database: 
        "01": [SC_GOLD_BEC_DB_O, SC_GOLD_GLB_DB_O]
    - name: GOLD_GENERAL_BEC_DEV_READER
      account:  []
      database:
        "01": [SC_GOLD_BEC_DB_R, SC_GOLD_GLB_DB_R]
    - name: GOLD_GENERAL_BPE_DEV_DEVELOPER
      account:  []    
      database: 
        "01": [SC_GOLD_BPE_DB_O, SC_GOLD_GLB_DB_O]
    - name: GOLD_GENERAL_BPE_DEV_READER
      account:  []
      database:
        "01": [SC_GOLD_BPE_DB_R, SC_GOLD_GLB_DB_R]
    - name: GOLD_GENERAL_HTC_DEV_DEVELOPER
      account:  []    
      database: 
        "01": [SC_GOLD_HTC_DB_O, SC_GOLD_GLB_DB_O]
    - name: GOLD_GENERAL_HTC_DEV_READER
      account:  []
      database:
        "01": [SC_GOLD_HTC_DB_R, SC_GOLD_GLB_DB_R]
    - name: GOLD_GENERAL_BUS_DEV_DEVELOPER
      account:  []    
      database: 
        "01": [SC_GOLD_BUS_DB_O, SC_GOLD_GLB_DB_O]
    - name: GOLD_GENERAL_BUS_DEV_READER
      account:  []
      database:
        "01": [SC_GOLD_BUS_DB_R, SC_GOLD_GLB_DB_R]
    - name: GOLD_GENERAL_GLB_DEV_DEVELOPER
      account:  []    
      database: 
        "01": [SC_GOLD_GLB_DB_O]
    - name: GOLD_GENERAL_GLB_DEV_READER
      account:  []
      database:
        "01": [SC_GOLD_GLB_DB_R]

privileges:
  # account:
  #   CREATE ROLE: [SECURITY_ADMIN]
  #   CREATE USER: [SECURITY_ADMIN]
  #   CREATE WAREHOUSE: [SECURITY_ADMIN]
  #   CREATE DATABASE: [SECURITY_ADMIN]
  #   MONITOR USAGE : [SECURITY_ADMIN]

  warehouse:
    WH_LOADING_DEV:
      USAGE: [WH_LOADING_DEV_USAGE]
      MONITOR: [WH_LOADING_DEV_ADMIN]
    WH_TRANSFORMATION_DEV:
      USAGE: [WH_TRANSFORMATION_DEV_USAGE]
      MONITOR: [WH_TRANSFORMATION_DEV_ADMIN]
    WH_ANALYTICS_DEV:
      USAGE: [WH_ANALYTICS_DEV_USAGE]
      MONITOR: [WH_ANALYTICS_DEV_ADMIN]

  # database:
  #   GOVERNANCE:
  #     USAGE: [ANALYST]
  #     MODIFY: [DATA_ADMIN]
  #     CREATE DATABASE ROLE: [DATA_ADMIN]
  #     CREATE SCHEMA: [DATA_ADMIN]

  # schema:
  #   AUDIT:
  #     USAGE: [ANALYST]
  #     MODIFY: [DATA_ADMIN]
  #     CREATE TABLE: [DEVELOPER]
  #     CREATE VIEW: [DEVELOPER]
  #     CREATE TAG: [SECURITY_ADMIN]
  #   MONITOR:
  #     USAGE: [ANALYST]
  #     MODIFY: [DATA_ADMIN]
  #     CREATE TABLE: [DEVELOPER]
  #     CREATE VIEW: [DEVELOPER]


##### privilegios de warehouse
##### grant ownership al respectivo admin ''''''
##### roles silver y gold  ''''''''
##### pruebas de uso

