# --------------------------------
# name: Snowflake Role Hierarchy
# owner: admin
# description: Define parent-child relationships
# version: 1.0
# --------------------------------

roles:
  ADMIN: [DEVELOPER]
  DEVELOPER: [READER]
  READER: [SC_BRONZE_AS400_BAR_DB_R]
