# --------------------------------
# name: Snowflake Account Roles
# owner: security
# description: Define parent-child relationships and privileges
# version: 1.0
# --------------------------------

roles:
  system_role:
    - name: SYSADMIN
      account:  [TERRAFORM_DEV_ADMIN]
      database: []
  ownership_roles:
    DEV: [TERRAFORM_DEV_ADMIN]
  account:
    # MAIN ROLE
    - name: TERRAFORM_DEV_ADMIN
      account:  [WH_LOADING_DEV_ADMIN, WH_TRANSFORMATION_DEV_ADMIN, WH_ANALYTICS_DEV_ADMIN, AC_GLB_DEV_DATA_ENGINEER]
      database: []

    # WAREHOUSE ROLES
    - name: WH_LOADING_DEV_ADMIN
      account:  [WH_LOADING_DEV_USAGE]
      database: []
    - name: WH_LOADING_DEV_USAGE
      account:  []
      database: []
    - name: WH_TRANSFORMATION_DEV_USAGE
      account:  []
      database: []
    - name: WH_TRANSFORMATION_DEV_ADMIN
      account:  [WH_TRANSFORMATION_DEV_USAGE]
      database: []
    - name: WH_ANALYTICS_DEV_USAGE
      account:  []
      database: []
    - name: WH_ANALYTICS_DEV_ADMIN
      account:  [WH_ANALYTICS_DEV_USAGE]
      database: []
    # BRONZE ACCOUNT ROLES
    - name: BRONZE_GENERAL_BMX_DEV_DEVELOPER
      account:  []
      database:
        "01": [SC_BRONZE_E1P_BMX_DB_O, SC_BRONZE_VENDING_BMX_DB_O, SC_BRONZE_OPE_GLB_DB_O]
    - name: BRONZE_GENERAL_BMX_DEV_READER
      account:  []
      database:
        "01": [SC_BRONZE_E1P_BMX_DB_R, SC_BRONZE_VENDING_BMX_DB_R, SC_BRONZE_OPE_GLB_DB_R]
    - name: BRONZE_GENERAL_BAR_DEV_DEVELOPER
      account:  []
      database:
        "01": [SC_BRONZE_AS400_BAR_DB_O, SC_BRONZE_OPE_GLB_DB_O]
    - name: BRONZE_GENERAL_BAR_DEV_READER
      account:  []
      database:
        "01": [SC_BRONZE_AS400_BPE_DB_R, SC_BRONZE_OPE_GLB_DB_R]
    - name: BRONZE_GENERAL_BPE_DEV_DEVELOPER
      account:  []
      database:
        "01": [SC_BRONZE_AS400_BPE_DB_O, SC_BRONZE_OPE_GLB_DB_O]
    - name: BRONZE_GENERAL_BPE_DEV_READER
      account:  []
      database:
        "01": [SC_BRONZE_AS400_BPE_DB_R, SC_BRONZE_OPE_GLB_DB_R]
    - name: BRONZE_GENERAL_BEC_DEV_DEVELOPER
      account:  []    
      database:
        "01": [SC_BRONZE_AS400_BEC_DB_O, SC_BRONZE_OPE_GLB_DB_O]
    - name: BRONZE_GENERAL_BEC_DEV_READER
      account:  []
      database:
        "01": [SC_BRONZE_AS400_BEC_DB_R, SC_BRONZE_OPE_GLB_DB_R]
    - name: BRONZE_GENERAL_HTC_DEV_DEVELOPER
      account:  []    
      database:
        "01": [SC_BRONZE_AS400_HTC_DB_O, SC_BRONZE_OPE_GLB_DB_O]
    - name: BRONZE_GENERAL_HTC_DEV_READER
      account:  []
      database:
        "01": [SC_BRONZE_AS400_HTC_DB_R, SC_BRONZE_OPE_GLB_DB_R]
    - name: BRONZE_GENERAL_GLB_DEV_DEVELOPER
      account:  []    
      database:
        "01": [SC_BRONZE_OPE_GLB_DB_O]
    - name: BRONZE_GENERAL_GLB_DEV_READER
      account:  []
      database:
        "01": [SC_BRONZE_OPE_GLB_DB_R]
    - name: BRONZE_GENERAL_BUS_DEV_DEVELOPER
      account:  []    
      database:
        "01": [SC_BRONZE_SNOWF_BUS_DB_O, SC_BRONZE_OPE_GLB_DB_O]
    - name: BRONZE_GENERAL_BUS_DEV_READER
      account:  []
      database:
        "01": [SC_BRONZE_SNOWF_BUS_DB_R, SC_BRONZE_OPE_GLB_DB_R]
 
  # DATA_ENGINEER LOCAL ROLES
    - name: AC_BMX_DEV_DATA_ENGINEER
      account:  [BRONZE_GENERAL_BMX_DEV_DEVELOPER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BAR_DEV_DATA_ENGINEER
      account:  [BRONZE_GENERAL_BAR_DEV_DEVELOPER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BEC_DEV_DATA_ENGINEER
      account:  [BRONZE_GENERAL_BEC_DEV_DEVELOPER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BPE_DEV_DATA_ENGINEER
      account:  [BRONZE_GENERAL_BPE_DEV_DEVELOPER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_HTC_DEV_DATA_ENGINEER
      account:  [BRONZE_GENERAL_HTC_DEV_DEVELOPER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BUS_DEV_DATA_ENGINEER
      account:  [BRONZE_GENERAL_BUS_DEV_DEVELOPER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
   
 
  # DATA_ENGINEER GLOBAL ROLE
    - name: AC_GLB_DEV_DATA_ENGINEER
      account:  [BRONZE_GENERAL_BMX_DEV_DEVELOPER, BRONZE_GENERAL_BAR_DEV_DEVELOPER, BRONZE_GENERAL_BEC_DEV_DEVELOPER, BRONZE_GENERAL_BPE_DEV_DEVELOPER, BRONZE_GENERAL_HTC_DEV_DEVELOPER, BRONZE_GENERAL_BUS_DEV_DEVELOPER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
 
 
  # BUSINESS_INTELLIGENCE LOCAL ROLES
    - name: AC_BMX_DEV_BUSINESS_INTELLIGENCE
      account:  [BRONZE_GENERAL_BMX_DEV_READER, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BAR_DEV_BUSINESS_INTELLIGENCE
      account:  [BRONZE_GENERAL_BAR_DEV_READER, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BEC_DEV_BUSINESS_INTELLIGENCE
      account:  [BRONZE_GENERAL_BEC_DEV_READER, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BPE_DEV_BUSINESS_INTELLIGENCE
      account:  [BRONZE_GENERAL_BPE_DEV_READER, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_HTC_DEV_BUSINESS_INTELLIGENCE
      account:  [BRONZE_GENERAL_HTC_DEV_READER, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
    - name: AC_BUS_DEV_BUSINESS_INTELLIGENCE
      account:  [BRONZE_GENERAL_BUS_DEV_READER, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
 
    # BUSINESS_INTELLIGENCE GLOBAL ROLE
    - name: AC_GLB_DEV_BUSINESS_INTELLIGENCE
      account:  [BRONZE_GENERAL_BMX_DEV_READER, BRONZE_GENERAL_BAR_DEV_READER, BRONZE_GENERAL_BEC_DEV_READER, BRONZE_GENERAL_BPE_DEV_READER, BRONZE_GENERAL_HTC_DEV_READER, BRONZE_GENERAL_BUS_DEV_READER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []
 
    # DATA_ARCHITECT GLOBAL ROLE
    - name: AC_GLB_DEV_DATA_ARCHITECT
      account:  [BRONZE_GENERAL_BMX_DEV_READER, BRONZE_GENERAL_BAR_DEV_READER, BRONZE_GENERAL_BEC_DEV_READER, BRONZE_GENERAL_BPE_DEV_READER, BRONZE_GENERAL_HTC_DEV_READER, BRONZE_GENERAL_BUS_DEV_READER, WH_LOADING_DEV_USAGE, WH_TRANSFORMATION_DEV_USAGE, WH_ANALYTICS_DEV_USAGE]
      database: []

privileges:
##### privilegios de warehouse
##### grant ownership al respectivo admin
##### roles silver y gold
##### pruebas de uso

