# --------------------------------
# name: Snowflake Privileges Mapping
# owner: admin
# description: Privilege to Account Role Matrix
# version: 1.0
# --------------------------------

privileges:
  account:
    CREATE ROLE: []
    CREATE USER: []
    CREATE WAREHOUSE: []
    CREATE DATABASE: []
    MONITOR USAGE : []

  warehouse:
    WH_LOADING_DEV:
    USAGE: [READER]
    MODIFY: [ADMIN]

  database:
    BD_AC_DEV_01:
      USAGE: [READER]
      MODIFY: [ADMIN]
      CREATE DATABASE ROLE: [ADMIN]
      CREATE SCHEMA: [ADMIN]

  schema:
    SC_BRONZE_AS400_BAR:
      USAGE: [READER]
      MODIFY: [ADMIN]
      CREATE TABLE: [DEVELOPER]
      CREATE VIEW: [DEVELOPER]
      CREATE TAG: []